"""Configuration file for the Sphinx documentation builder."""

# See http://www.sphinx-doc.org/en/master/config for all config options.

# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

# Project information.
project = 'Cloudmarker'
copyright = '2018, Cloudmarker Authors and Contributors'
author = 'Cloudmarker Authors and Contributors'

# Short version in X.Y format and full release version.
version = ''
release = ''

extensions = ['sphinx.ext.autodoc']

# Default options generated by sphinx-quickstart.
templates_path = ['_templates']
source_suffix = '.rst'
master_doc = 'index'
language = None
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
pygments_style = None
html_theme = 'alabaster'
html_static_path = ['_static']
htmlhelp_basename = 'Cloudmarkerdoc'

latex_elements = {}
latex_documents = [
    (master_doc, 'Cloudmarker.tex', 'Cloudmarker Documentation',
     'Cloudmarker Authors and Contributors', 'manual'),
]

man_pages = [
    (master_doc, 'cloudmarker', 'Cloudmarker Documentation',
     [author], 1)
]

texinfo_documents = [
    (master_doc, 'Cloudmarker', 'Cloudmarker Documentation',
     author, 'Cloudmarker', 'One line description of project.',
     'Miscellaneous'),
]

epub_title = project
epub_exclude_files = ['search.html']
