"""Configuration file for the Sphinx documentation builder."""

# See http://www.sphinx-doc.org/en/master/config for all config options.

import os
import sys

# The package to document with autodoc is in the parent directory, so
# add it to sys.path. This also helps in importing the package and using
# its attributes in this file.
sys.path.insert(0, os.path.abspath('..'))

# To prevent isort, pycodestyle, and pylint from complaining about an
# import in the middle of the code, we place this import in a try-except
# block. This is probably a good thing anyway. If we mess up sys.path
# above, the import failure would be caught and handled gracefully.
try:
    import cloudmarker
except ImportError as e:
    print('{}: {}'.format(type(e).__name__, str(e)), file=sys.stderr)
    sys.exit(1)

# Project information.
project = 'Cloudmarker'
copyright = '2018, {}'.format(cloudmarker.__author__)
author = cloudmarker.__author__

# Short version in X.Y format and full release version.
version = '.'.join(cloudmarker.__version__.split('.')[:2])
release = cloudmarker.__version__

# Use Napoleon to support Google style docstrings:
# https://www.sphinx-doc.org/en/master/usage/extensions/example_google.html
#
# Use Intersphinx to link to cross-reference Python's official
# documentation.
extensions = ['sphinx.ext.napoleon', 'sphinx.ext.intersphinx']

# Default options generated by sphinx-quickstart.
templates_path = ['_templates']
source_suffix = '.rst'
master_doc = 'index'
language = None
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
pygments_style = None

# Do not set a theme so that Read the Docs can choose its default one.
# html_theme = 'alabaster'

html_static_path = ['_static']
htmlhelp_basename = 'Cloudmarkerdoc'

latex_elements = {}
latex_documents = [
    (master_doc, 'Cloudmarker.tex', 'Cloudmarker Documentation',
     'Cloudmarker Authors and Contributors', 'manual'),
]

man_pages = [
    (master_doc, 'cloudmarker', 'Cloudmarker Documentation',
     [author], 1)
]

texinfo_documents = [
    (master_doc, 'Cloudmarker', 'Cloudmarker Documentation',
     author, 'Cloudmarker', cloudmarker.__doc__.splitlines()[0],
     'Miscellaneous'),
]

epub_title = project
epub_exclude_files = ['search.html']

# Include __init__ method's docstring too to document a class.
autoclass_content = 'both'

intersphinx_mapping = {'python': ('https://docs.python.org/3', None)}
